version: "3.9"

services:
  supabasebot:
    build: .
    container_name: supabasebot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./service-account.json:/usr/src/app/service-account.json:ro
      - ./src:/usr/src/app/src:ro
